// PM2 Ecosystem Configuration
// Manages all Heady AI Platform services
module.exports = {
    apps: [
        // ── Core Services ──
        {
            name: 'heady-manager',
            script: 'heady-manager.js',
            cwd: '/home/headyme/Heady',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
                PORT: 3301,
                HF_TOKEN: process.env.HF_TOKEN || '',
            },
            max_memory_restart: '512M',
            min_uptime: '10s',
            max_restarts: 10,
            restart_delay: 3000,
            kill_timeout: 5000,
            listen_timeout: 10000,
            watch: false,
            error_file: '/home/headyme/Heady/logs/manager-error.log',
            out_file: '/home/headyme/Heady/logs/manager-out.log',
            merge_logs: true,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
        },
        {
            name: 'hcfp-auto-success',
            script: 'scripts/hcfp-full-auto.js',
            cwd: '/home/headyme/Heady',
            instances: 1,
            exec_mode: 'fork',
            env: {
                NODE_ENV: 'production',
            },
            max_memory_restart: '256M',
            min_uptime: '10s',
            max_restarts: 5,
            restart_delay: 5000,
            watch: false,
            error_file: '/home/headyme/Heady/logs/hcfp-error.log',
            out_file: '/home/headyme/Heady/logs/hcfp-out.log',
            merge_logs: true,
            log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
        },

        // ── Site Servers ──
        // Each site runs a static file server on its assigned port
        ...[
            { name: 'headybuddy', port: 9000 },
            { name: 'headysystems', port: 9001 },
            { name: 'headyconnection', port: 9002 },
            { name: 'headymcp', port: 9003 },
            { name: 'headyio', port: 9004 },
            { name: 'headyme', port: 9005 },
            { name: 'headyapi', port: 9006 },
            { name: 'headyos', port: 9007 },
            { name: 'heady-discord', port: 9008 },
            { name: 'heady-discord-connector', port: 9009 },
            { name: 'headyio-com', port: 9010 },
            { name: 'headybuddy-org', port: 9011 },
            { name: 'headyconnection-org', port: 9012 },
            { name: 'headyme-com', port: 9013 },
            { name: 'headymcp-com', port: 9014 },
            { name: 'headysystems-com', port: 9015 },
            { name: '1ime1', port: 9016 },
            { name: 'admin-ui', port: 9017 },
            { name: 'instant', port: 9018 },
            { name: 'headydocs', port: 9019 },
            { name: 'headyweb', port: 3000 },
        ].map(site => ({
            name: `site-${site.name}`,
            script: 'npx',
            args: `serve dist -l ${site.port} -s --no-clipboard`,
            cwd: `/home/headyme/sites/${site.name}`,
            instances: 1,
            exec_mode: 'fork',
            env: { NODE_ENV: 'production' },
            max_memory_restart: '128M',
            min_uptime: '5s',
            max_restarts: 3,
            restart_delay: 2000,
            watch: false,
            autorestart: true,
        })),
    ],
};
