// ╔══════════════════════════════════════════════════════════════════╗
// ║  HEADY™ Agent Handoff — pure core v1.0.0                          ║
// ║  Side-effect-free: parses git deltas, shapes the checkpoint, and   ║
// ║  renders the handoff bundle. The CLI (handoff.mjs) feeds it real   ║
// ║  git/gate output. Pure → fully unit-testable.                     ║
// ║  © 2026 HeadySystems Inc. — Eric Haywood, Founder                 ║
// ╚══════════════════════════════════════════════════════════════════╝

export const CHECKPOINT_SCHEMA = "heady.handoff.checkpoint/v1";
export const BUNDLE_SCHEMA = "heady.handoff.bundle/v1";

/** Parse a stored checkpoint; returns null on absent/invalid (→ first run). */
export function loadCheckpoint(raw) {
  if (!raw) return null;
  try {
    const o = typeof raw === "string" ? JSON.parse(raw) : raw;
    if (!o || o.schema !== CHECKPOINT_SCHEMA || typeof o.head !== "string") return null;
    return o;
  } catch {
    return null;
  }
}

/** Build the next checkpoint to persist after a successful handoff. */
export function nextCheckpoint(head, nowIso, prev) {
  return {
    schema: CHECKPOINT_SCHEMA,
    head,
    at: nowIso,
    previousHead: prev?.head ?? null,
    runCount: (prev?.runCount ?? 0) + 1,
  };
}

const STATUS_LABEL = { A: "Added", M: "Modified", D: "Deleted", R: "Renamed", C: "Copied", T: "TypeChanged" };

/** Parse `git diff --name-status` into [{ status, path, from? }]. */
export function parseNameStatus(text) {
  if (!text) return [];
  return text
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .map((line) => {
      const parts = line.split(/\t/);
      const code = parts[0][0]; // R100 → R, C75 → C
      if ((code === "R" || code === "C") && parts.length >= 3) {
        return { status: code, from: parts[1], path: parts[2] };
      }
      return { status: code, path: parts[parts.length - 1] };
    });
}

/** Group files by status with counts. */
export function summarizeFiles(files) {
  const groups = {};
  for (const f of files) (groups[f.status] ??= []).push(f);
  const counts = Object.fromEntries(Object.entries(groups).map(([k, v]) => [k, v.length]));
  return { groups, counts, total: files.length };
}

// Field delimiter the CLI emits in git log --pretty (unit separator U+001F — never in commit text).
export const FIELD_SEP = "";

/** Parse `git log` lines delimited by FIELD_SEP into commit records. */
export function parseCommits(text) {
  if (!text) return [];
  return text
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .map((line) => {
      const [sha, subject, author, date] = line.split(FIELD_SEP);
      return { sha, subject, author, date };
    });
}

function verdictGlyph(ok) {
  return ok ? "✓" : "✗";
}

/**
 * Render the full agent-readable handoff bundle (markdown).
 * @param {object} b
 *  - nowIso, head, headShort, branch, sinceRef, sinceShort, firstRun
 *  - commits: [{sha,subject,author,date}]
 *  - files:   [{status,path,from?}]
 *  - stat:    string (git diff --stat tail)
 *  - verification: [{name, ok, detail}]
 *  - contextFiles: [{path, exists, note}]
 *  - uncommitted: [string]
 */
export function renderBundle(b) {
  const { groups, counts, total } = summarizeFiles(b.files ?? []);
  const allGreen = (b.verification ?? []).every((v) => v.ok);
  const out = [];

  out.push(`# Heady Agent Handoff — ${b.nowIso}`);
  out.push("");
  out.push(
    `> Generated by \`/heady-handoff\`. Brings a fresh agent fully up to speed on everything ` +
      `since ${b.firstRun ? "the repository baseline" : `the last handoff (\`${b.sinceShort}\`)`}.`
  );
  out.push("");

  // 1. TL;DR
  out.push("## 1. TL;DR");
  out.push("");
  out.push(`- **Branch:** \`${b.branch}\` at HEAD \`${b.headShort}\`${b.firstRun ? " *(first run — baseline)*" : ""}`);
  out.push(`- **Since:** ${b.firstRun ? "baseline" : `\`${b.sinceShort}\``} → ${(b.commits ?? []).length} commit(s), ${total} file(s) changed`);
  out.push(
    `- **Verification:** ${(b.verification ?? []).map((v) => `${v.name} ${verdictGlyph(v.ok)}`).join(" · ") || "—"}` +
      `${allGreen ? "" : "  ⚠️ see §4 for failures"}`
  );
  if ((b.uncommitted ?? []).length) out.push(`- **Uncommitted in tree:** ${b.uncommitted.length} file(s) (§6)`);
  out.push("");

  // 2. Commits
  out.push("## 2. Commits since last handoff");
  out.push("");
  if ((b.commits ?? []).length === 0) {
    out.push("_No new commits in range._");
  } else {
    for (const c of b.commits) out.push(`- \`${c.sha}\` ${c.subject}${c.author ? ` — ${c.author}` : ""}`);
  }
  out.push("");

  // 3. Files changed
  out.push("## 3. Files changed");
  out.push("");
  if (total === 0) {
    out.push("_No file changes in range._");
  } else {
    for (const code of ["A", "M", "D", "R", "C", "T"]) {
      const g = groups[code];
      if (!g || g.length === 0) continue;
      out.push(`### ${STATUS_LABEL[code] ?? code} (${counts[code]})`);
      for (const f of g) out.push(`- \`${f.path}\`${f.from ? ` (from \`${f.from}\`)` : ""}`);
      out.push("");
    }
    if (b.stat) {
      out.push("```");
      out.push(b.stat.trim());
      out.push("```");
      out.push("");
    }
  }

  // 4. Verification
  out.push("## 4. Verification results");
  out.push("");
  out.push("| Gate | Status | Detail |");
  out.push("|------|--------|--------|");
  for (const v of b.verification ?? []) {
    out.push(`| ${v.name} | ${v.ok ? "PASS ✓" : "FAIL ✗"} | ${(v.detail ?? "").replace(/\|/g, "\\|").slice(0, 160)} |`);
  }
  out.push("");

  // 5. Context to read (ordered)
  out.push("## 5. Context to read (in order)");
  out.push("");
  for (const c of b.contextFiles ?? []) {
    out.push(`- ${c.exists ? "" : "⚠️ (missing) "}\`${c.path}\`${c.note ? ` — ${c.note}` : ""}`);
  }
  out.push("");

  // 6. Open threads
  out.push("## 6. Open threads / not-done");
  out.push("");
  const failed = (b.verification ?? []).filter((v) => !v.ok);
  if (failed.length === 0 && (b.uncommitted ?? []).length === 0) {
    out.push("_All gates green; working tree clean at handoff time._");
  } else {
    for (const v of failed) out.push(`- ⚠️ Gate **${v.name}** is failing — ${(v.detail ?? "").slice(0, 200)}`);
    for (const u of b.uncommitted ?? []) out.push(`- Uncommitted: \`${u}\``);
  }
  out.push("");

  // 7. Optimal Execution Guidelines
  out.push("## 7. Optimal Execution Guidelines (Agent Primer)");
  out.push("");
  out.push("**For the incoming AI Agent:** To handle the Heady ecosystem optimally, adhere to the following operational parameters:");
  out.push("");
  out.push("### Core Operating Directives");
  out.push("- **Decisive Authority:** You gather input, but YOU make the final call. Act with certainty.");
  out.push("- **Strict Compliance:** Adhere completely to `AGENTS.md` and `SOURCE_OF_TRUTH.md` (Section 5).");
  out.push("- **Ownership:** You own the code you write. No placeholder implementations — no to-do/fix-me markers, no stubs. Write production-ready code. If an implementation is incomplete, fail the task and trigger a replan.");
  out.push("- **Proactive Advisory Mandate:** Always proactively identify and recommend infrastructure safeguards, cost-saving measures, and billing protections (e.g., usage-caps, enterprise configurations) whenever relevant context appears. Never wait for the user to ask.");
  out.push("");
  out.push("### Architectural Mandates");
  out.push("- **Liquid Architecture & RAM-First Computing:** 3D vector space is the source of truth, APIs project from it.");
  out.push("- **No Magic Numbers:** All retry intervals, pool sizes, and limits must be derived from `phi-constants.js` (φ-scaling where `phi=1.618`).");
  out.push("- **ESM Only:** No CommonJS `require()`. Use `import/export`.");
  out.push("- **Zero Localhost:** All URLs must come from environment variables.");  // heady-allow:no-localhost — primer prose quoting the law, not a URL
  out.push("- **Zod Validation:** All API inputs must be validated at service boundaries.");
  out.push("- **UI & Styling:** Use Vite SPAs + Vanilla Web Components. Style with Sacred Geometry tokens (fibonacci spacing, glassmorphism) and NO heavy frameworks like React unless strictly necessary for 3D canvas.");
  out.push("- **Pipeline Compliance:** Comply with the 22-stage HCFullPipeline orchestration and Continuous Semantic Logic (CSL) gating rules.");
  out.push("");
  out.push("### Style & Detail");
  out.push("- Output must be highly structured, heavily utilizing Markdown (tables, bolded headers, code fences). Be intensely technical, precise, and entirely devoid of conversational filler.");
  out.push("- Segment your reasoning into distinct architectural phases (e.g., Ingestion, Synthesis, Execution).");
  out.push("");

  // 8. Checkpoint
  out.push("## 8. Checkpoint");
  out.push("");
  out.push(`- **Previous:** ${b.firstRun ? "—" : `\`${b.sinceShort}\``}`);
  out.push(`- **New:** \`${b.headShort}\` (next \`/heady-handoff\` reports from here)`);
  out.push("");
  out.push("---");
  out.push("*© 2026 HeadySystems Inc. — Eric Haywood, Founder*");
  out.push("");

  return out.join("\n");
}
