// ╔══════════════════════════════════════════════════════════════════╗
// ║  HEADY™ Agent Handoff — pure core v1.1.0                          ║
// ║  Side-effect-free: parses git deltas, shapes the checkpoint, and   ║
// ║  renders the handoff bundle. The CLI (handoff.mjs) feeds it real   ║
// ║  git/gate output. Pure → fully unit-testable.                     ║
// ║  Made with ❤️ by HeadySystems Inc.                                ║
// ╚══════════════════════════════════════════════════════════════════╝

export const CHECKPOINT_SCHEMA = "heady.handoff.checkpoint/v1";
export const BUNDLE_SCHEMA = "heady.handoff.bundle/v1";

/** Parse a stored checkpoint; returns null on absent/invalid (→ first run). */
export function loadCheckpoint(raw) {
  if (!raw) return null;
  try {
    const o = typeof raw === "string" ? JSON.parse(raw) : raw;
    if (!o || o.schema !== CHECKPOINT_SCHEMA || typeof o.head !== "string") return null;
    return o;
  } catch {
    return null;
  }
}

/** Build the next checkpoint to persist after a successful handoff. */
export function nextCheckpoint(head, nowIso, prev) {
  return {
    schema: CHECKPOINT_SCHEMA,
    head,
    at: nowIso,
    previousHead: prev?.head ?? null,
    runCount: (prev?.runCount ?? 0) + 1,
  };
}

const STATUS_LABEL = { A: "Added", M: "Modified", D: "Deleted", R: "Renamed", C: "Copied", T: "TypeChanged" };

/** Parse `git diff --name-status` into [{ status, path, from? }]. */
export function parseNameStatus(text) {
  if (!text) return [];
  return text
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .map((line) => {
      const parts = line.split(/\t/);
      const code = parts[0][0]; // R100 → R, C75 → C
      if ((code === "R" || code === "C") && parts.length >= 3) {
        return { status: code, from: parts[1], path: parts[2] };
      }
      return { status: code, path: parts[parts.length - 1] };
    });
}

/** Group files by status with counts. */
export function summarizeFiles(files) {
  const groups = {};
  for (const f of files) (groups[f.status] ??= []).push(f);
  const counts = Object.fromEntries(Object.entries(groups).map(([k, v]) => [k, v.length]));
  return { groups, counts, total: files.length };
}

// Field delimiter the CLI emits in git log --pretty (unit separator U+001F — never in commit text).
export const FIELD_SEP = "";

/** Parse `git log` lines delimited by FIELD_SEP into commit records. */
export function parseCommits(text) {
  if (!text) return [];
  return text
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean)
    .map((line) => {
      const [sha, subject, author, date] = line.split(FIELD_SEP);
      return { sha, subject, author, date };
    });
}

function verdictGlyph(ok) {
  return ok ? "✓" : "✗";
}

function verificationGlyph(result) {
  return result.status === "error" ? "⚠" : verdictGlyph(result.ok);
}

function verificationLabel(result) {
  if (result.ok) return "PASS ✓";
  return result.status === "error" ? "ERROR ⚠" : "FAIL ✗";
}

/**
 * Render the full agent-readable handoff bundle (markdown).
 * @param {object} b
 *  - nowIso, head, headShort, branch, sinceRef, sinceShort, firstRun
 *  - commits: [{sha,subject,author,date}]
 *  - files:   [{status,path,from?}]
 *  - stat:    string (git diff --stat tail)
 *  - verification: [{name, ok, detail}]
 *  - contextFiles: [{path, exists, note}]
 *  - uncommitted: [string]
 */
export function renderBundle(b) {
  const { groups, counts, total } = summarizeFiles(b.files ?? []);
  const verificationPerformed = (b.verification ?? []).length > 0;
  const allGreen = verificationPerformed && b.verification.every((v) => v.ok);
  const out = [];

  out.push(`# Heady Agent Handoff — ${b.nowIso}`);
  out.push("");
  out.push(
    `> Generated by \`/heady-handoff\`. Brings a fresh agent fully up to speed on everything ` +
      `since ${b.firstRun ? "the repository baseline" : `the last handoff (\`${b.sinceShort}\`)`}.`
  );
  out.push("");

  // 1. TL;DR
  out.push("## 1. TL;DR");
  out.push("");
  out.push(`- **Branch:** \`${b.branch}\` at HEAD \`${b.headShort}\`${b.firstRun ? " *(first run — baseline)*" : ""}`);
  out.push(`- **Since:** ${b.firstRun ? "baseline" : `\`${b.sinceShort}\``} → ${(b.commits ?? []).length} commit(s), ${total} file(s) changed`);
  out.push(
    `- **Verification:** ${(b.verification ?? []).map((v) => `${v.name} ${verificationGlyph(v)}`).join(" · ") || "not run *(unverified)*"}` +
      `${verificationPerformed && !allGreen ? "  ⚠️ see §4 for failures" : ""}`
  );
  if ((b.uncommitted ?? []).length) out.push(`- **Uncommitted in tree:** ${b.uncommitted.length} file(s) (§6)`);
  out.push("");

  // 2. Commits
  out.push("## 2. Commits since last handoff");
  out.push("");
  if ((b.commits ?? []).length === 0) {
    out.push("_No new commits in range._");
  } else {
    for (const c of b.commits) out.push(`- \`${c.sha}\` ${c.subject}${c.author ? ` — ${c.author}` : ""}`);
  }
  out.push("");

  // 3. Files changed
  out.push("## 3. Files changed");
  out.push("");
  if (total === 0) {
    out.push("_No file changes in range._");
    out.push("");
  } else {
    for (const code of ["A", "M", "D", "R", "C", "T"]) {
      const g = groups[code];
      if (!g || g.length === 0) continue;
      out.push(`### ${STATUS_LABEL[code] ?? code} (${counts[code]})`);
      for (const f of g) out.push(`- \`${f.path}\`${f.from ? ` (from \`${f.from}\`)` : ""}`);
      out.push("");
    }
    if (b.stat) {
      out.push("```");
      out.push(b.stat.trim());
      out.push("```");
      out.push("");
    }
  }

  // 4. Verification
  out.push("## 4. Verification results");
  out.push("");
  if (!verificationPerformed) {
    out.push("_Verification not run; this bundle is unverified._");
  } else {
    out.push("| Gate | Status | Detail |");
    out.push("|------|--------|--------|");
    for (const v of b.verification ?? []) {
      out.push(`| ${v.name} | ${verificationLabel(v)} | ${(v.detail ?? "").replace(/\|/g, "\\|").slice(0, 160)} |`);
    }
  }
  out.push("");

  // 5. Context to read (ordered)
  out.push("## 5. Context to read (in order)");
  out.push("");
  for (const c of b.contextFiles ?? []) {
    out.push(`- ${c.exists ? "" : "⚠️ (missing) "}\`${c.path}\`${c.note ? ` — ${c.note}` : ""}`);
  }
  out.push("");

  // 6. Open threads
  out.push("## 6. Open threads / not-done");
  out.push("");
  const failed = (b.verification ?? []).filter((v) => !v.ok);
  if (!verificationPerformed) {
    out.push("- ⚠️ Verification was not run; this bundle is unverified.");
    for (const u of b.uncommitted ?? []) out.push(`- Uncommitted: \`${u}\``);
  } else if (failed.length === 0 && (b.uncommitted ?? []).length === 0) {
    out.push("_All gates green; working tree clean at handoff time._");
  } else {
    for (const v of failed) {
      const state = v.status === "error" ? "could not execute" : "is failing";
      out.push(`- ⚠️ Gate **${v.name}** ${state} — ${(v.detail ?? "").slice(0, 200)}`);
    }
    for (const u of b.uncommitted ?? []) out.push(`- Uncommitted: \`${u}\``);
  }
  out.push("");

  // 7. Authority-aware execution primer
  out.push("## 7. Authority-Aware Execution Primer");
  out.push("");
  out.push("**For the incoming agent:** Treat this generated primer as explanatory context. Current `AGENTS.md`, accepted ADRs, validated facts/contracts, and implementation evidence remain authoritative.");
  out.push("");
  out.push("### Core Operating Directives");
  out.push("- **Scoped Agency:** Act autonomously within the user's request while preserving non-bypassable human-review, cryptographic-governance, credential, destructive, and production gates.");
  out.push("- **Authority Order:** Follow `AGENTS.md`, governance, accepted ADRs, validated facts/contracts, implementation evidence, then living explanations and plans/history.");
  out.push("- **Ownership:** You own the code you write. No placeholder implementations — no to-do/fix-me markers, no stubs. Write production-ready code. If an implementation is incomplete, fail the task and trigger a replan.");
  out.push("- **Proactive Advisory Mandate:** Always proactively identify and recommend infrastructure safeguards, cost-saving measures, and billing protections (e.g., usage-caps, enterprise configurations) whenever relevant context appears. Never wait for the user to ask.");
  out.push("");
  out.push("### Architectural Mandates");
  out.push("- **Durable Data Authority:** Neon/pgvector is retrieval authority; Redis/KV is best-effort hot state and Vectorize is a reconstructible edge projection. Verify ADR-0051 activation before claiming source-ledger cutover.");
  out.push("- **No Magic Numbers:** Derive retry intervals, pool sizes, and limits from `@heady/phi-math`.");
  out.push("- **ESM Only:** No CommonJS `require()`. Use `import/export`.");
  out.push("- **Zero Localhost:** All URLs must come from environment variables.");  // heady-allow:no-localhost — primer prose quoting the law, not a URL
  out.push("- **Zod Validation:** All API inputs must be validated at service boundaries.");
  out.push("- **UI & Styling:** Use Vite SPAs + Vanilla Web Components. Style with Sacred Geometry tokens (fibonacci spacing, glassmorphism) and NO heavy frameworks like React unless strictly necessary for 3D canvas.");
  out.push("- **Pipeline Compliance:** Use current governed workflows and CSL gates; historical workflow names do not create authority.");
  out.push("");
  out.push("### Style & Detail");
  out.push("- Lead with outcomes, use only the formatting needed for clarity, and separate observed facts from interpretation.");
  out.push("");

  // 8. Checkpoint
  out.push("## 8. Checkpoint");
  out.push("");
  out.push(`- **Previous:** ${b.firstRun ? "—" : `\`${b.sinceShort}\``}`);
  out.push(`- **New:** \`${b.headShort}\` (next \`/heady-handoff\` reports from here)`);
  out.push("");
  out.push("---");
  out.push("*Made with ❤️ by HeadySystems Inc.*");
  out.push("");

  return out.join("\n");
}
