#!/usr/bin/env node
import fs from 'fs/promises';
import path from 'path';

/**
 * generate_hue_reports.mjs
 * 
 * Lazy-generator for the Heady Understanding Engine (HUE) Documentation Library.
 * Usage: node generate_hue_reports.mjs [workflow-name]
 * Example: node generate_hue_reports.mjs heady-autopilot
 * 
 * If a workflow name is provided, it generates a templated HUE report for that workflow.
 * If no argument is provided, it scans .agents/workflows/ and lists missing reports.
 */

const WORKFLOW_DIR = path.resolve(process.cwd(), '.agents/workflows');
const REPORTS_DIR = path.resolve(process.cwd(), 'docs/understanding_reports');

async function main() {
    const target = process.argv[2];

    try {
        await fs.access(REPORTS_DIR);
    } catch {
        await fs.mkdir(REPORTS_DIR, { recursive: true });
    }

    if (!target) {
        console.log('🔍 Scanning for missing HUE reports...');
        const workflows = await fs.readdir(WORKFLOW_DIR);
        const reports = await fs.readdir(REPORTS_DIR);
        
        let missing = 0;
        for (const wf of workflows) {
            if (wf.endsWith('.md')) {
                const basename = path.basename(wf, '.md');
                const reportName = `hue_${basename.replace(/-/g, '_')}.md`;
                if (!reports.includes(reportName)) {
                    console.log(`- Missing: ${basename} (Run: node generate_hue_reports.mjs ${basename})`);
                    missing++;
                }
            }
        }
        console.log(`\nTotal missing reports: ${missing}`);
        return;
    }

    // Generate specific report
    const basename = target.replace('.md', '');
    const workflowPath = path.join(WORKFLOW_DIR, `${basename}.md`);
    
    try {
        await fs.access(workflowPath);
    } catch {
        console.error(`❌ Workflow '${basename}' not found in ${WORKFLOW_DIR}`);
        process.exit(1);
    }

    const reportName = `hue_${basename.replace(/-/g, '_')}.md`;
    const reportPath = path.join(REPORTS_DIR, reportName);

    const template = `# HUE Understanding Report: \`/${basename}\`

## 1. Mechanism
*(How does this workflow operate at a technical level? What APIs/tools does it hit?)*
[TODO: Agent to fill]

## 2. Causality
*(Why does it work this way? What are the underlying dependencies?)*
[TODO: Agent to fill]

## 3. Teleology
*(What is the ultimate purpose of this capability in the Heady ecosystem?)*
[TODO: Agent to fill]

## 4. Relations
*(How does this connect to other skills, workflows, or data pipelines?)*
[TODO: Agent to fill]

## 5. Effect
*(What are the direct outputs and state changes caused by this workflow?)*
[TODO: Agent to fill]

## 6. Blast Radius
*(What is the worst-case scenario if this fails or is misused?)*
[TODO: Agent to fill]

## 7. Normativity
*(What trade-offs were made in its design? Cost vs Speed vs Accuracy?)*
[TODO: Agent to fill]

## 8. Agency
*(How much autonomy does this workflow have? Does it require human CSL gating?)*
[TODO: Agent to fill]

## 9. Confidence
*(How stable is this workflow? Is there high risk of semantic drift?)*
[TODO: Agent to fill]

## 10. Execution
*(How is it monitored? What are its fallback paths?)*
[TODO: Agent to fill]

---
*Generated by HUE Lazy-Loader. Trigger an agent to flesh out these sections via Deep Research.*
`;

    await fs.writeFile(reportPath, template, 'utf-8');
    console.log(`✅ Generated template: ${reportPath}`);
}

main().catch(console.error);
